dist: trusty
language: go

go:
  - 1.13.x

os:
  - linux
  - windows
  - osx

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_script:
  - go get -t ./...

script:
  - go test ./test