dist: trusty
language: go

env:
  - PHP_VERSION=7.2
  - PHP_VERSION=7.3
  - PHP_VERSION=7.4

go:
  - 1.13.x

os:
  - linux

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_script:
  - go get -t ./...

script:
  - go test ./test